/*****************************************************************************************
    Name    : Interface_ServiceException 
    Desc    : This class extends the standard exception class and will be used to throw custom exception from Interface related service classes
              
                       
                            
Modification Log : 
---------------------------------------------------------------------------
     Developer              Date            Description
---------------------------------------------------------------------------
    Vipul Jain          20 JUNE 2014        Created
******************************************************************************************/

public class Interface_ServiceException extends exception {
    
}