public with sharing class PartnerPointsCatalogContentItem {
	public String	ppContentId {get; set; }
	public String	contentId {get; set; }
	public String	title {get; set; }
	public Integer	points {get; set; }
	public Integer	contentSize {get; set; }
	public String	fileType {get; set; }
	public Boolean	isActive {get; set; }
	public String	subcategory {get; set; }
	public String	trackId {get; set; }
	public String	excludeBatchId {get; set; }
}